print("Quanto ganha-se por hora?")
dinheiroPorHora = int(input())
print("Quantas horas trabalhou-se?")
horasTrabalhadas = int(input())
print("Salário Final:")
print(dinheiroPorHora * horasTrabalhadas)